### ISSUE TITLE
Clear ScrapedAuthors collection upon successful operation

### ISSUE THREAD

**Issue by pratikGhodke1** [karelumair/Quotes-API#58]
Clear ScrapedAuthors collection once authors are added/updated to `Authors` collection successfully. Could be a periodic cleanup.

**Comment by karelumair** [comment]
- [x] Cron Jobs.
- [x] Mongodb / Flask Scheduled clean up.
- [x] Collection for storing scarped author status.
- [x] Only one shared task to scarpe both quotes and authors.
- [x] Update Task response status.
