### ISSUE TITLE
Error while running docker-compose container

### ISSUE THREAD

**Issue by pratikGhodke1** [karelumair/Quotes-API#75]
**1. Tried starting service using `docker-compose build up --build`. There getting below errors.**

![image](https://user-images.githubusercontent.com/115528882/221881425-3969635c-a546-40a2-83a3-7921ad5a21ee.png)

**Fix**: add context inside build in docker-compose as -

```docker
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
```

<hr>

**2. Error while `step to install chrome driver`**

![image](https://user-images.githubusercontent.com/115528882/221881958-9a562f93-d555-485d-b1d3-afca8385f6d3.png)
 
##### UPDATE: Probably temporary error, worked second time I ran it :v:

**Comment by karelumair** [comment]
Its working fine at my end.

**Comment by karelumair** [comment]
Try using `docker compose up --build` Instead of using package `docker-compose`
